#!/bin/bash
#PBS -l nodes=2:ppn=28,walltime=00:30:00
#PBS -N hw4job
#PBS -q debug

module load shared
module load mvapich2/gcc/64/2.2rc1

cd$HOME

mpirun -np 4 ./3kgraph > $HOME/graph4p2.txt
mpirun -np 28 ./3kgraph > $HOME/graph28p2.txt
mpirun -np 56 ./3kgraph > $HOME/graph56p2.txt


